-- MySQL Script generated by MySQL Workbench
-- Tue Oct 28 17:46:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema census_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema census_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `census_db` DEFAULT CHARACTER SET utf8 ;
USE `census_db` ;

-- -----------------------------------------------------
-- Table `census_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `census_db`.`address` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(100) NOT NULL,
  `number` INT NOT NULL,
  `complement` VARCHAR(100) NULL,
  `neighborhood` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `zipcode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `census_db`.`income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `census_db`.`income` (
  `id_income` INT NOT NULL AUTO_INCREMENT,
  `monthly_income` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_income`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `census_db`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `census_db`.`education` (
  `id_education` INT NOT NULL AUTO_INCREMENT,
  `education_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_education`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `census_db`.`marital_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `census_db`.`marital_status` (
  `id_marital_status` INT NOT NULL AUTO_INCREMENT,
  `marital_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marital_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `census_db`.`disability` (
  `id_disability` INT NOT NULL AUTO_INCREMENT,
  `disability` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_disability`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `census_db`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `census_db`.`person` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `birth` DATE NOT NULL,
  `age` INT NOT NULL GENERATED ALWAYS AS (TIMESTAMPDIFF(YEAR, birth, CURDATE())
  ) STORED,
  `gender` VARCHAR(45) NOT NULL,
  `document` VARCHAR(45) NOT NULL,
  `address_id_address` INT NOT NULL,
  `income_id_income` INT NULL,
  `education_id_education` INT NULL,
  `marital_status_id_marital_status` INT NULL,
  `disability_id_disability` INT NOT NULL,
  PRIMARY KEY (`id_person`),
  INDEX `fk_person_address_idx` (`address_id_address` ASC) VISIBLE,
  INDEX `fk_person_income1_idx` (`income_id_income` ASC) VISIBLE,
  INDEX `fk_person_education1_idx` (`education_id_education` ASC) VISIBLE,
  INDEX `fk_person_marital_status1_idx` (`marital_status_id_marital_status` ASC) VISIBLE,
  INDEX `fk_person_disability1_idx` (`disability_id_disability` ASC) VISIBLE,
  CONSTRAINT `fk_person_address`
    FOREIGN KEY (`address_id_address`)
    REFERENCES `census_db`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_income1`
    FOREIGN KEY (`income_id_income`)
    REFERENCES `census_db`.`income` (`id_income`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_education1`
    FOREIGN KEY (`education_id_education`)
    REFERENCES `census_db`.`education` (`id_education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_marital_status1`
    FOREIGN KEY (`marital_status_id_marital_status`)
    REFERENCES `census_db`.`marital_status` (`id_marital_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_disability1`
    FOREIGN KEY (`disability_id_disability`)
    REFERENCES `census_db`.`disability` (`id_disability`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
